on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Test WebExtensions
jobs:
  test:
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Testing WebExtensions
        run: |
          make -C webextensions test
